# Generated by Django 4.2.5 on 2023-09-14 17:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Content_Blog',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='Image_Blog',
            field=models.ImageField(default='default_image.jpg', upload_to='blog_images/'),
        ),
    ]
