# Generated by Django 4.2.5 on 2023-09-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blog_content_blog_blog_image_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Image_Blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='Image_blog',
            field=models.ImageField(default='blog_images/default.jpg', upload_to='blog_images/'),
        ),
    ]
