# Generated by Django 4.2.5 on 2023-09-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_remove_blog_image_blog_blog_image_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Image_blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='Image_Blog',
            field=models.ImageField(default='blog_images/default_image.jpg', upload_to='blog_images/'),
        ),
    ]
